name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: donde estoy
      run: pwd
    - name: listado 
      run: ls -lrt
    - name: Build the Docker image
      run: |
        cd src/app
        docker build -t frontend:$(date +%s) .
        docker images
