name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: roxsross12

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: donde estoy
      run: pwd
    - name: listado 
      run: ls -lrt
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Build the Docker image
      run: |
        cd src/app
        docker build -t frontend:$(date +%s) .
        docker images
        docker tag frontend:$(date +%s) $REGISTRY/frontend:$(date +%s)
        docker push $REGISTRY/frontend:$(date +%s)
